name: Bug Report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: What did you do?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-outcome
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual-outcome
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: mod-list
    attributes:
      label: List of installed mods
      description: Please provide a list of all mods installed when the issue occurred.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please paste the full game logs here. verify that the logs are not truncated.
      value: |
        <details>
        <summary>Logs</summary>
        
        ```
        <!-- Paste your logs here -->
        ```
        </details>
    validations:
      required: true

  - type: input
    id: mod-version
    attributes:
      label: Mod Version
      description: Which version of the mod are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: checkboxes
    id: compatibility-warning
    attributes:
      label: Compatibility
      options:
        - label: I acknowledge that if other mods are installed, this issue might be closed as "won't fix" if it is determined to be an incompatibility.
          required: true
